title: "William Merfalen"
theme: "eon"
baseURL: "https://wmerfalen.github.io/twitter-clone-challenge"
#baseURL: 'http://localhost:8801'
# for multiple authors, see
# https://discourse.gohugo.io/t/site-author-usage/31459/8?u=coolaj86
Author:
  name: "William Merfalen"
  email: "wmerfalen@gmail.com"
copyright: "© William Merfalen"
languageCode: "en-us"

Params:
  gravatar: true
  show_edit: "Suggest Edit"
  git_repo: "https://github.com/wmerfalen/twitter-clone-challenge"
  git_branch: "main"
  git_host: "github"
  utterences_repo: "wmerfalen/twitter-clone-challenge"
  utterences_term: "pathname"
  enableGitInfo: true
  enableEmoji: true

markup:
  goldmark:
    renderer:
    # unsafe allows use of HTML and JavaScript in your Markdown
    # disable if your blog allows posts from untrusted authors
    unsafe: true
